#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/smolvlm/modular_smolvlm.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_smolvlm.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2025 the HuggingFace Inc. team. All rights reserved.
# Written by Orr Zohar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import math

import numpy as np
import torch
from torchvision.transforms.v2 import functional as tvF

from ...image_processing_utils import BatchFeature
from ...image_transforms import group_images_by_shape, reorder_images
from ...image_utils import (
    IMAGENET_STANDARD_MEAN,
    IMAGENET_STANDARD_STD,
    ImageInput,
    PILImageResampling,
    SizeDict,
    make_nested_list_of_images,
)
from ...processing_utils import ImagesKwargs, Unpack
from ...utils import TensorType, auto_docstring as _auto_docstring_real

def auto_docstring(*args, **kwargs):
    try:
        result = _auto_docstring_real(*args, **kwargs)
    except (ValueError, Exception):
        if args and callable(args[0]):
            return args[0]
        return lambda cls: cls
    if args and callable(args[0]):
        return result
    def _safe_apply(cls):
        try:
            return result(cls)
        except (ValueError, Exception):
            return cls
    return _safe_apply

# TorchvisionBackend was split into its own module in a newer transformers version.
# Fall back to BaseImageProcessorFast and supply rescale_and_normalize if needed.
try:
    from ...image_processing_backends import TorchvisionBackend
except (ImportError, ModuleNotFoundError):
    try:
        from ...image_processing_utils_fast import BaseImageProcessorFast as _BackendBase
    except ImportError:
        from ...image_processing_utils import BaseImageProcessor as _BackendBase

    class TorchvisionBackend(_BackendBase):
        """Compatibility shim: TorchvisionBackend → BaseImageProcessorFast for older transformers."""

        def rescale_and_normalize(self, images, do_rescale, rescale_factor,
                                  do_normalize, image_mean, image_std):
            """Fused rescale + normalize on a [B, C, H, W] float tensor."""
            if do_rescale:
                images = images.to(dtype=torch.float32) * rescale_factor
            if do_normalize:
                mean = torch.tensor(image_mean, dtype=images.dtype, device=images.device)
                std  = torch.tensor(image_std,  dtype=images.dtype, device=images.device)
                images = (images - mean[None, :, None, None]) / std[None, :, None, None]
            return images

print("[custom_smolvlm] image_processing_smolvlm.py loaded — CUSTOM IMAGE PROCESSOR ACTIVE")


class SmolVLMImageProcessorKwargs(ImagesKwargs, total=False):
    """
    do_image_splitting (`bool`, *optional*, defaults to `True`):
        Whether to split the image into sub-images concatenated with the original image. They are split into patches
        such that each patch has a size of `max_image_size["height"]` x `max_image_size["width"]`.
    max_image_size (`Dict`, *optional*, defaults to `{"longest_edge": 364}`):
        Maximum resolution of the patches of images accepted by the model. This is a dictionary containing the key "longest_edge".
    return_row_col_info (`bool`, *optional*, defaults to `False`):
        Whether to return the row and column information of the images.
    """

    do_image_splitting: bool
    max_image_size: dict[str, int]
    return_row_col_info: bool


MAX_IMAGE_SIZE = 4096  # 4k resolution as absolute maximum


def _resize_output_size_rescale_to_max_len(
    height: int, width: int, min_len: int | None = 1, max_len: int | None = None
) -> tuple[int, int]:
    """
    Get the output size of the image after resizing given a dictionary specifying the max and min sizes.
    Args:
        height (`int`):
            Height of the input image.
        width (`int`):
            Width of the input image.
        min_len (`int`, *optional*, defaults to 1):
            Minimum size of the output image.
        max_len (`int`, *optional*, defaults to the maximum size of the image):
            Maximum size of the output image.
    Returns:
        The output size of the image after resizing.
    """
    max_len = max(height, width) if max_len is None else max_len
    aspect_ratio = width / height

    if width >= height:
        width = max_len
        height = int(width / aspect_ratio)
        if height % 2 != 0:
            height += 1
    elif height > width:
        height = max_len
        width = int(height * aspect_ratio)
        if width % 2 != 0:
            width += 1

    # Avoid resizing to a size smaller than min_len
    height = max(height, min_len)
    width = max(width, min_len)
    return height, width


def _resize_output_size_scale_below_upper_bound(
    height: int, width: int, max_len: dict[str, int] | None = None
) -> tuple[int, int]:
    """
    Get the output size of the image after resizing given a dictionary specifying the max and min sizes.
    Args:
        height (`int`):
            Height of the input image.
        width (`int`):
            Width of the input image.
        max_len (`Dict[str, int]`, *optional*, defaults to the maximum size of the image):
            Defines the maximum dimensions of the image.
    Returns:
        The output size of the image after resizing.
    """
    max_len = max(height, width) if max_len is None else max_len

    aspect_ratio = width / height
    if width >= height and width > max_len:
        width = max_len
        height = int(width / aspect_ratio)
    elif height > width and height > max_len:
        height = max_len
        width = int(height * aspect_ratio)

    # Avoid resizing to a size smaller than 1
    height = max(height, 1)
    width = max(width, 1)
    return height, width


def get_resize_output_image_size(
    image: "torch.Tensor",
    resolution_max_side: int,
) -> tuple[int, int]:
    """
    Get the output size of the image after resizing given a dictionary specifying the max and min sizes.
    Args:
        image (`torch.Tensor`):
            Image to resize.
        resolution_max_side (`int`):
            The longest edge of the image will be resized to this value. The shortest edge will be resized to keep the
            input aspect ratio.
    Returns:
        The output size of the image after resizing.
    """
    height, width = image.shape[-2:]

    # Find the output size, when rescaling the longest edge to max_len and preserving the aspect ratio
    height, width = _resize_output_size_rescale_to_max_len(height, width, max_len=resolution_max_side)
    # Find the output size when scaling the image to be below the MAX_IMAGE_SIZE
    height, width = _resize_output_size_scale_below_upper_bound(height, width, max_len=MAX_IMAGE_SIZE)
    return height, width


def get_max_height_width(images_list: list[list["torch.Tensor|np.ndarray"]]) -> tuple[int, int]:
    """
    Get the maximum height and width across all images in a batch.
    """
    image_sizes = []
    for images in images_list:
        for image in images:
            image_sizes.append(image.shape[-2:])

    max_height = max(size[0] for size in image_sizes)
    max_width = max(size[1] for size in image_sizes)
    return (max_height, max_width)


def get_num_channels(images_list: list[list["torch.Tensor|np.ndarray"]]) -> int:
    """
    Get the number of channels across all images in a batch. Handle empty sublists like in [[], [image]].
    """
    for images in images_list:
        if images:
            return images[0].shape[0]

    raise ValueError("No images found in the batch.")


def get_device_from_images(images_list: list[list["torch.Tensor"]]) -> "torch.device":
    """
    Get the device from the first non-empty element in a nested list of images.
    Handle empty sublists like in [[], [image]].
    """
    for images in images_list:
        if images:
            return images[0].device


@auto_docstring
class SmolVLMImageProcessor(TorchvisionBackend):
    resample = PILImageResampling.LANCZOS
    image_mean = IMAGENET_STANDARD_MEAN
    image_std = IMAGENET_STANDARD_STD
    size = {"longest_edge": 4 * 364}
    max_image_size = {"longest_edge": 364}
    do_resize = True
    do_rescale = True
    do_normalize = True
    do_convert_rgb = True
    do_image_splitting = True
    do_pad = True
    return_row_col_info = False
    valid_kwargs = SmolVLMImageProcessorKwargs
    model_input_names = ["pixel_values", "pixel_attention_mask"]

    def __init__(self, **kwargs: Unpack[SmolVLMImageProcessorKwargs]):
        super().__init__(**kwargs)
        self._focus_point = None  # set via preprocess(focus_point=...) before each call

    @auto_docstring
    def preprocess(self, images: ImageInput, focus_point=None, **kwargs: Unpack[SmolVLMImageProcessorKwargs]) -> BatchFeature:
        """
        focus_point (`tuple`, *optional*):
            ``(x, y)`` coordinates of the region of interest. When provided,
            image splitting is replaced by dynamic focus partitioning: one local
            crop centred on ``(x, y)`` (covering ≈25 % of the image) + one
            global overview → exactly 2 partitions total.
            Values in [0, 1] are treated as normalised fractions; values > 1
            as absolute pixel coordinates.
        """
        self._focus_point = focus_point
        try:
            return super().preprocess(images, **kwargs)
        finally:
            self._focus_point = None  # always reset, even on exception

    def _prepare_images_structure(self, images: ImageInput, expected_ndims: int = 3) -> ImageInput:
        """
        Prepare a nested images structure for processing.
        """
        # Checks for `str` in case of URL/local path and optionally loads images
        images = self.fetch_images(images)
        return make_nested_list_of_images(images, expected_ndims=expected_ndims)

    def resize(
        self,
        image: "torch.Tensor",
        size: SizeDict,
        resample: "PILImageResampling | tvF.InterpolationMode | int | None" = None,
        **kwargs,
    ) -> "torch.Tensor":
        """
        Resize an image. The longest edge of the image is resized to size.longest_edge, with the shortest edge
        resized to keep the input aspect ratio. Can also be used with size.height and size.width.
        Args:
            image (`torch.Tensor`):
                Image to resize.
            size (`SizeDict`):
                Size of the output image.
            resample (`PILImageResampling | tvF.InterpolationMode | int | None`, *optional*):
                Resampling filter to use when resizing the image.
        """
        if size.longest_edge:
            new_size = get_resize_output_image_size(image, resolution_max_side=size.longest_edge)
        elif size.height and size.width:
            new_size = (size.height, size.width)
        else:
            raise ValueError("size must be a dictionary with key 'longest_edge' or 'height' and 'width'.")

        return super().resize(image, SizeDict(height=new_size[0], width=new_size[1]), resample=resample, **kwargs)

    def split_images(
        self,
        images: torch.Tensor,
        max_image_size: dict[str, int],
        resample: "PILImageResampling | tvF.InterpolationMode | int | None" = None,
    ):
        """
        Split an image into squares of side max_image_size and the original image resized to max_image_size.
        That means that a single image becomes a sequence of images.
        This is a "trick" to spend more compute on each image with no changes in the vision encoder.
        1) If one side of the original image is larger than `max_image_size`, resize it to `max_image_size` while preserving the aspect ratio.
        2) Divide the resulting image into `ceil(height / max_image_size)` x `ceil(width / max_image_size)`
        sub-images of the same size each (image_size, image_size). Typically, 364x364.
        3) Returns the list of the crops and the original image, in addition to the number of splits for the height and the width.
        Args:
            images (`torch.Tensor`):
                Images to split.
            max_image_size (`Dict[str, int]`):
                Maximum size of the output image. If the image is larger than this size, it will be split into
                patches of this size, and the original image will be concatenated with the patches, resized to max_size.
            resample (`PILImageResampling | tvF.InterpolationMode | int | None`, *optional*):
                Resampling filter to use when resizing the image.
        """
        batch_size, num_channels, height, width = images.size()
        height_dim, width_dim = 2, 3

        max_height = max_width = max_image_size["longest_edge"]

        frames = []
        if height > max_height or width > max_width:
            # Calculate the number of splits
            num_splits_h = math.ceil(height / max_height)
            num_splits_w = math.ceil(width / max_width)

            # Split the images by height, then by width
            frames = (
                images.unfold(height_dim, size=max_height, step=max_height)
                .unfold(width_dim, size=max_width, step=max_width)
                .contiguous()
                .view(batch_size, num_channels, -1, max_height, max_width)
                .permute(0, 2, 1, 3, 4)
            )  # batch_size x n_frames x num_channels x height x width

            # For the global image at the end, we resize it to match the max_image_size, for cpu memory efficiency
            global_image_height, global_image_width = max_height, max_width
            images = self.resize(
                images, SizeDict(height=global_image_height, width=global_image_width), resample=resample
            )

            frames = torch.cat((frames, images.unsqueeze(1)), dim=1)
        else:
            num_splits_h, num_splits_w = 0, 0
            frames = images.unsqueeze(1)

        num_splits_h = [num_splits_h] * batch_size
        num_splits_w = [num_splits_w] * batch_size

        return frames, num_splits_h, num_splits_w

    def split_images_around_point(
        self,
        images: torch.Tensor,
        point: tuple,
        max_image_size: dict,
        resample=None,
    ):
        """
        Create exactly 2 partitions from each image:
          1. A square local crop **centered at ``point``** that covers ≈25 % of
             the original image area  (crop_side = sqrt(0.25 * H * W)).
          2. The full original image resized to max_image_size (global overview).

        Args:
            images:         (batch_size, C, H, W) float tensor.
            point:          (x, y) where x is the column and y is the row.
                            Values in [0, 1] → treated as normalised fractions.
                            Values > 1       → treated as absolute pixel coords.
            max_image_size: dict with key ``"longest_edge"``.
            resample:       resampling filter forwarded to self.resize.

        Returns:
            frames : (batch_size, 2, C, max_size, max_size)
                      dim-1 order: [local_crop, global_image]
            rows   : [1] * batch_size  — signals a 1×1 sub-grid to the processor
            cols   : [1] * batch_size
        """
        batch_size, num_channels, height, width = images.size()
        max_size = max_image_size["longest_edge"]

        px, py = float(point[0]), float(point[1])

        # Normalised [0,1] → absolute pixel coordinates
        if 0.0 <= px <= 1.0 and 0.0 <= py <= 1.0:
            px = px * width
            py = py * height

        px, py = int(round(px)), int(round(py))

        # Square crop whose area = 25 % of the original image
        crop_side = max(1, int(math.sqrt(0.25 * height * width)))

        # Clamp so the crop stays fully inside the image
        x1 = max(0, min(px - crop_side // 2, width - crop_side))
        y1 = max(0, min(py - crop_side // 2, height - crop_side))
        x2 = x1 + crop_side
        y2 = y1 + crop_side

        print(f"[focus] point=({px},{py}), crop=[{x1}:{x2}, {y1}:{y2}], "
              f"crop_side={crop_side}, area_ratio={crop_side**2 / (height*width):.3f}")

        # Local crop → resize to (max_size, max_size)
        local_crop = images[:, :, y1:y2, x1:x2].contiguous()
        local_crop_resized = self.resize(
            local_crop, SizeDict(height=max_size, width=max_size), resample=resample
        )

        # Global: full image → resize to (max_size, max_size)
        global_image = self.resize(
            images, SizeDict(height=max_size, width=max_size), resample=resample
        )

        # Stack: (batch_size, 2, C, max_size, max_size)
        frames = torch.stack([local_crop_resized, global_image], dim=1)

        rows = [1] * batch_size  # 1×1 sub-grid → processor renders <row_1_col_1> + global
        cols = [1] * batch_size

        return frames, rows, cols

    def resize_for_vision_encoder(
        self,
        image: torch.Tensor,
        vision_encoder_max_size: int,
        resample: "PILImageResampling | tvF.InterpolationMode | int | None" = None,
    ):
        """
        Resize images to be multiples of `vision_encoder_max_size` while preserving the aspect ratio.
        Args:
            image (`torch.Tensor`):
                Images to resize.
            vision_encoder_max_size (`int`):
                Maximum size of the output image. If the image is larger than this size, it will be split into
                patches of this size, and the original image will be concatenated with the patches, resized to max_size.
            resample (`PILImageResampling | tvF.InterpolationMode | int | None`, *optional*):
                Resampling filter to use when resizing the image.
        """
        height, width = image.size()[-2:]

        aspect_ratio = width / height
        if width >= height:
            width = math.ceil(width / vision_encoder_max_size) * vision_encoder_max_size
            height = int(width / aspect_ratio)
            height = math.ceil(height / vision_encoder_max_size) * vision_encoder_max_size
        elif height > width:
            height = math.ceil(height / vision_encoder_max_size) * vision_encoder_max_size
            width = int(height * aspect_ratio)
            width = math.ceil(width / vision_encoder_max_size) * vision_encoder_max_size
        new_size = SizeDict(height=height, width=width)
        return self.resize(image, size=new_size, resample=resample)

    def pad(
        self,
        image: torch.Tensor,
        padded_size: tuple[int, int],
        fill: int = 0,
        return_pixel_mask: bool = True,
    ):
        original_size = image.shape[-2:]
        padding_bottom = padded_size[0] - original_size[0]
        padding_right = padded_size[1] - original_size[1]

        if padding_bottom < 0 or padding_right < 0:
            raise ValueError(
                f"Padding dimensions are negative. Please make sure that the padded size is larger than the "
                f"original size. Got padded size: {padded_size}, original size: {original_size}."
            )

        # Only pad if necessary
        if original_size != padded_size:
            padding = (0, 0, padding_right, padding_bottom)
            image = tvF.pad(image, padding, fill=fill, padding_mode="constant")

        # Make a pixel mask for the image, where 1 indicates a valid pixel and 0 indicates padding.
        pixel_mask = None
        if return_pixel_mask:
            pixel_mask = torch.zeros_like(image[..., 0, :, :], dtype=torch.int64)
            pixel_mask[: original_size[0], : original_size[1]] = 1

        return image, pixel_mask

    def _preprocess(
        self,
        images: list[list["torch.Tensor"]],
        do_resize: bool = None,
        size: SizeDict = None,
        resample: "PILImageResampling | tvF.InterpolationMode | int | None" = None,
        do_rescale: bool = None,
        rescale_factor: float = None,
        do_normalize: bool = None,
        image_mean: float | list[float] | None = None,
        image_std: float | list[float] | None = None,
        do_pad: bool | None = None,
        do_image_splitting: bool | None = None,
        max_image_size: dict[str, int] | None = None,
        return_row_col_info: bool | None = None,
        disable_grouping: bool | None = None,
        return_tensors: str | TensorType | None = None,
        **kwargs,
    ) -> BatchFeature:
        """
        Process a batch of images for the model.
        """
        # Fall back to class-level defaults for any arg the older base class didn't pass
        if do_resize is None:
            do_resize = self.do_resize
        if size is None:
            size = SizeDict(**self.size) if isinstance(self.size, dict) else self.size
        if resample is None:
            resample = self.resample
        if do_rescale is None:
            do_rescale = self.do_rescale
        if rescale_factor is None:
            rescale_factor = getattr(self, "rescale_factor", 1.0 / 255.0)
        if do_normalize is None:
            do_normalize = self.do_normalize
        if image_mean is None:
            image_mean = self.image_mean
        if image_std is None:
            image_std = self.image_std
        if do_pad is None:
            do_pad = self.do_pad
        if do_image_splitting is None:
            do_image_splitting = self.do_image_splitting
        if max_image_size is None:
            max_image_size = self.max_image_size
        if return_row_col_info is None:
            return_row_col_info = self.return_row_col_info
        if disable_grouping is None:
            disable_grouping = kwargs.pop("disable_grouping", False)

        grouped_images, grouped_images_index = group_images_by_shape(
            images, is_nested=True, disable_grouping=disable_grouping
        )
        resized_images_grouped = {}
        for shape, stacked_images in grouped_images.items():
            if do_resize:
                stacked_images = self.resize(stacked_images, size, resample=resample)
            resized_images_grouped[shape] = stacked_images
        resized_images = reorder_images(resized_images_grouped, grouped_images_index, is_nested=True)

        grouped_images, grouped_images_index = group_images_by_shape(
            resized_images, is_nested=True, disable_grouping=disable_grouping
        )
        split_images_grouped = {}
        if do_image_splitting:
            rows_grouped = {}
            cols_grouped = {}
            focus_point = getattr(self, '_focus_point', None)
            for shape, stacked_images in grouped_images.items():
                if focus_point is not None:
                    # ── Dynamic focus partitioning: local crop + global = 2 tiles ──
                    stacked_images, rows, cols = self.split_images_around_point(
                        stacked_images, focus_point,
                        max_image_size=max_image_size, resample=resample,
                    )
                else:
                    # ── Original grid-based partitioning (unchanged) ──────────────
                    stacked_images = self.resize_for_vision_encoder(
                        stacked_images, max_image_size["longest_edge"], resample=resample
                    )
                    stacked_images, rows, cols = self.split_images(
                        stacked_images, max_image_size=max_image_size, resample=resample
                    )
                split_images_grouped[shape] = stacked_images
                rows_grouped[shape] = rows
                cols_grouped[shape] = cols
            processed_images = reorder_images(split_images_grouped, grouped_images_index, is_nested=True)
            rows = reorder_images(rows_grouped, grouped_images_index, is_nested=True)
            cols = reorder_images(cols_grouped, grouped_images_index, is_nested=True)
            # flattenened the doubly nested list to a nested list
            for i, group_images in enumerate(processed_images):
                processed_images[i] = [image for sublist in group_images for image in sublist]
        else:
            for shape, stacked_images in grouped_images.items():
                # We square the images to max_image_size
                stacked_images = self.resize(
                    image=stacked_images,
                    size=SizeDict(height=max_image_size["longest_edge"], width=max_image_size["longest_edge"]),
                    resample=resample,
                )
                split_images_grouped[shape] = stacked_images
            processed_images = reorder_images(split_images_grouped, grouped_images_index, is_nested=True)
            rows = [[0] * len(images) for images in processed_images]
            cols = [[0] * len(images) for images in processed_images]
        # Group images by size for further processing
        # Needed in case do_resize is False, or resize returns images with different sizes
        grouped_images, grouped_images_index = group_images_by_shape(
            processed_images, is_nested=True, disable_grouping=disable_grouping
        )
        processed_images_grouped = {}
        for shape, stacked_images in grouped_images.items():
            # Fused rescale and normalize
            stacked_images = self.rescale_and_normalize(
                stacked_images, do_rescale, rescale_factor, do_normalize, image_mean, image_std
            )
            processed_images_grouped[shape] = stacked_images
        processed_images = reorder_images(processed_images_grouped, grouped_images_index, is_nested=True)
        if do_pad:
            # Get max images per batch
            max_num_images = max(len(images_) for images_ in processed_images)
            max_height, max_width = get_max_height_width(processed_images)
            num_channels = get_num_channels(processed_images)
            device = get_device_from_images(processed_images)

            processed_images_padded = torch.zeros(
                len(processed_images),
                max_num_images,
                *(num_channels, max_height, max_width),
                device=device,
            )
            pixel_attention_masks = torch.zeros(
                len(processed_images),
                max_num_images,
                *(max_height, max_width),
                device=device,
            )
            for i, images in enumerate(processed_images):
                for j, image in enumerate(images):
                    processed_images_padded[i, j], pixel_attention_masks[i, j] = self.pad(
                        image, (max_height, max_width)
                    )
            processed_images = processed_images_padded

        if do_pad:
            data = {"pixel_values": processed_images, "pixel_attention_mask": pixel_attention_masks}
        elif return_tensors == "pt":
            data = {"pixel_values": torch.stack([torch.stack(images) for images in processed_images])}
        else:
            data = {"pixel_values": processed_images}
        # This is needed for generating correct text inputs in the processor - we don't pad to the max number of images
        encoding = BatchFeature(data=data, tensor_type=return_tensors)

        if return_row_col_info:
            encoding["rows"] = rows
            encoding["cols"] = cols

        return encoding

    def to_dict(self):
        encoder_dict = super().to_dict()
        encoder_dict.pop("_valid_processor_keys", None)
        encoder_dict.pop("return_row_col_info", None)
        return encoder_dict

    def get_number_of_image_patches(self, height: int, width: int, images_kwargs: dict):
        """
        A utility that returns number of image patches for a given image size.

        Args:
            height (`int`):
                Height of the input image.
            width (`int`):
                Width of the input image.
            images_kwargs (`dict`)
                Any kwargs to override defaults of the image processor.
        Returns:
            `int`: Number of patches per image.
        """
        do_image_splitting = images_kwargs.get("do_image_splitting", self.do_image_splitting)
        max_image_size = images_kwargs.get("max_image_size", self.max_image_size)
        size = images_kwargs.get("size", self.size)

        num_patches = num_rows = num_cols = 0
        if do_image_splitting:
            height, width = _resize_output_size_rescale_to_max_len(height, width, max_len=size["longest_edge"])
            height, width = _resize_output_size_scale_below_upper_bound(height, width, max_len=MAX_IMAGE_SIZE)
            aspect_ratio = width / height

            if width >= height:
                resized_width = math.ceil(width / max_image_size["longest_edge"]) * max_image_size["longest_edge"]
                resized_height = int(width / aspect_ratio)
                resized_height = math.ceil(height / max_image_size["longest_edge"]) * max_image_size["longest_edge"]
            elif height > width:
                resized_height = math.ceil(height / max_image_size["longest_edge"]) * max_image_size["longest_edge"]
                resized_width = int(height * aspect_ratio)
                resized_width = math.ceil(width / max_image_size["longest_edge"]) * max_image_size["longest_edge"]

            max_height = max_width = max_image_size["longest_edge"]
            if resized_height > max_height or resized_width > max_width:
                # Calculate the number of splits
                num_rows = math.ceil(resized_height / max_height)
                num_cols = math.ceil(resized_width / max_width)
                num_patches = num_rows * num_cols + 1

        return num_patches, num_rows, num_cols


def run_focus_partitioning_tests():
    """
    Tests for split_images_around_point / focus_point partitioning.

    Call this AFTER patching transformers (i.e. from run_inference.py):
        from transformers.models.smolvlm.image_processing_smolvlm import run_focus_partitioning_tests
        run_focus_partitioning_tests()

    Expected encoder output shape after these 2 partitions go through the
    SmolVLM2-256M vision encoder: (2, 64, 576)
      2   = num partitions (local crop + global)
      64  = (image_size / patch_size)^2 = (256/32)^2
      576 = vision encoder hidden_dim for SmolVLM2-256M
    """
    print("\n" + "=" * 60)
    print("Running focus-partitioning tests")
    print("=" * 60)

    proc = SmolVLMImageProcessor()
    max_size = proc.max_image_size["longest_edge"]  # 364

    # ── Test 1: output tensor shape (2 partitions) ────────────────────────────
    img = torch.rand(1, 3, 728, 728)
    frames, rows, cols = proc.split_images_around_point(
        img, point=(0.5, 0.5), max_image_size=proc.max_image_size
    )
    assert frames.shape == (1, 2, 3, max_size, max_size), \
        f"T1 FAIL: expected (1,2,3,{max_size},{max_size}), got {frames.shape}"
    assert rows == [1] and cols == [1], f"T1 FAIL: rows={rows} cols={cols}"
    print(f"  T1 PASS  shape={tuple(frames.shape)}  rows={rows}  cols={cols}")

    # ── Test 2: local crop area ≈ 25 % of original ───────────────────────────
    H, W = 800, 600
    crop_side = max(1, int(math.sqrt(0.25 * H * W)))
    ratio = (crop_side ** 2) / (H * W)
    assert abs(ratio - 0.25) < 0.02, f"T2 FAIL: area ratio {ratio:.4f}, expected ~0.25"
    print(f"  T2 PASS  crop_side={crop_side}  area_ratio={ratio:.4f}  (target=0.25)")

    # ── Test 3: focus point lies inside the local crop ───────────────────────
    H, W = 728, 728
    img3 = torch.rand(1, 3, H, W)
    px, py = int(0.3 * W), int(0.7 * H)       # off-centre point
    crop_side = max(1, int(math.sqrt(0.25 * H * W)))
    x1 = max(0, min(px - crop_side // 2, W - crop_side))
    y1 = max(0, min(py - crop_side // 2, H - crop_side))
    x2, y2 = x1 + crop_side, y1 + crop_side
    assert x1 <= px <= x2 and y1 <= py <= y2, \
        f"T3 FAIL: point ({px},{py}) outside crop [{x1}:{x2}, {y1}:{y2}]"
    print(f"  T3 PASS  point=({px},{py}) inside crop [{x1}:{x2}, {y1}:{y2}]")

    # ── Test 4: top-left corner point → crop clamped, still valid shape ───────
    img4 = torch.rand(1, 3, 728, 728)
    frames4, _, _ = proc.split_images_around_point(
        img4, point=(0.0, 0.0), max_image_size=proc.max_image_size
    )
    assert frames4.shape == (1, 2, 3, max_size, max_size), \
        f"T4 FAIL: corner-point shape {frames4.shape}"
    print(f"  T4 PASS  corner point (0,0) → shape {tuple(frames4.shape)}")

    # ── Test 5: bottom-right corner point → crop clamped ────────────────────
    img5 = torch.rand(1, 3, 728, 728)
    frames5, _, _ = proc.split_images_around_point(
        img5, point=(1.0, 1.0), max_image_size=proc.max_image_size
    )
    assert frames5.shape == (1, 2, 3, max_size, max_size), \
        f"T5 FAIL: corner-point shape {frames5.shape}"
    print(f"  T5 PASS  corner point (1,1) → shape {tuple(frames5.shape)}")

    # ── Test 6: absolute pixel coordinates ───────────────────────────────────
    img6 = torch.rand(1, 3, 728, 728)
    frames6, _, _ = proc.split_images_around_point(
        img6, point=(364.0, 364.0), max_image_size=proc.max_image_size
    )
    assert frames6.shape == (1, 2, 3, max_size, max_size), \
        f"T6 FAIL: pixel-coord shape {frames6.shape}"
    print(f"  T6 PASS  pixel coords (364,364) → shape {tuple(frames6.shape)}")

    # ── Test 7: full preprocess() integration via focus_point kwarg ──────────
    img7 = torch.rand(3, 728, 728)          # (C, H, W) — standard single-image input
    result = proc.preprocess([img7], return_tensors="pt", focus_point=(0.5, 0.5))
    pv = result["pixel_values"]
    assert pv.shape[1] == 2, \
        f"T7 FAIL: expected 2 partitions in pixel_values, got {pv.shape[1]}"
    print(f"  T7 PASS  preprocess pixel_values shape: {tuple(pv.shape)}")
    print(f"           (batch={pv.shape[0]}, partitions={pv.shape[1]}, "
          f"C={pv.shape[2]}, H={pv.shape[3]}, W={pv.shape[4]})")

    # ── Test 8: focus_point=None → original grid partitioning (never forced to 2) ──
    # Any image goes through: initial resize to longest_edge=1456 → grid split.
    # A 200×200 input upscales to 1456×1456 → 4×4+1=17 tiles (not 2).
    img8 = torch.rand(3, 200, 200)
    result8 = proc.preprocess([img8], return_tensors="pt", focus_point=None)
    pv8 = result8["pixel_values"]
    assert pv8.shape[1] != 2, \
        f"T8 FAIL: focus_point=None should use grid splitting, not focus (got 2)"
    print(f"  T8 PASS  focus_point=None → {pv8.shape[1]} partitions "
          f"(grid splitting active, not capped at 2)")

    print("\nAll 8 tests PASSED")
    print(f"\nNote: after the vision encoder, 2 partitions should produce shape")
    print(f"      (2, 64, 576) for SmolVLM2-256M  [2 patches × 64 tokens × 576 hidden]")
    print("=" * 60)


__all__ = ["SmolVLMImageProcessor", "run_focus_partitioning_tests"]
